=== t-logan/TestProject/DLC/bin/vehicleEmissions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epa.gov"
    xmlns="http://www.epa.gov" elementFormDefault="qualified">
    <xs:element name="vehicleEmissions"> </xs:element>
    <xs:element name="vehicle">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="vin" type="vinType" minOccurs="1" maxOccurs="1"/>
                <xs:element name="manufacturer" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="modelYear" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                <xs:element name="vehicleType" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="oilChangeDistance" type="xs:float" minOccurs="1" maxOccurs="1"/>
                <xs:element name="odometer" type="xs:float" minOccurs="1" maxOccurs="1"/>
                <xs:element name="comments" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="photo" type="xs:base64Binary"/>
                <xs:element name="emissions" type="emissionsType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- 
        Emissions data.
    -->
    <xs:complexType name="emissionsType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="dateTested" type="xs:date"/>
            <xs:element name="exhaustHC" type="xs:float"/>
            <xs:element name="nonExhaustHC" type="xs:float"/>
            <xs:element name="exhaustCO" type="xs:float"/>
            <xs:element name="exhaustNO2" type="xs:float"/>
        </xs:sequence>
    </xs:complexType>
    <!-- 
        VIN Number
    -->
    <xs:simpleType name="vinType">
        <xs:restriction base="xs:string">
            <xs:length value="17"/>
        </xs:restriction>
    </xs:simpleType>
 </xs:schema>

=== t-logan/TestProject/DLC/src/main/dat/vehicleEmissions.xml
<?xml version='1.0' encoding='UTF-8'?>
<vehicleEmissions xmlns="http://www.epa.gov" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.epa.gov vehicleEmissions.xsd"><vehicle><vin>2F228U31WMWGGOLC2</vin><manufacturer>Ford (Canada)</manufacturer><modelYear>1991</modelYear><vehicleType>LIGHT_DUTY_TRUCK</vehicleType><oilChangeDistance>181.0</oilChangeDistance><odometer>35399.0</odometer><comments>Fluxum flap dum dum. Foo bar zany somethingnew any words will do. Just trying to make some 123456789realistic text to plug into the comment field. Llijihgph wpokrepoj slkaligihe; lkjslijlie jsill. jjjFluxum flap dum dum. Foo bar zany somethingnew any words will do. Just trying to make some 123456789realistic text to plug into the comment field. Llijihgph wpokrepoj slkaligihe; lkjslijlie jsill. jjjFluxum flap dum dum. Foo bar zany somethingnew any words will do. Just trying to make some 123456789realistic text to plug into the comment field. Llijihgph wpokrepoj slkaligihe; lkjslijlie jsill. jjjFluxum flap dum dum. Foo bar zany somethingnew any words will do. Just trying to make some 123456789realistic text to plug into the comment field. Llijihgph wpokrepoj slkaligihe; lkjslijlie jsill. jjjFluxum flap dum dum. Foo bar zany somethingnew any words will do. Just trying to make some 123456789Fluxum flap dum dum. Foo bar zany somethingnew any words will do. Just trying to make some 123456789realistic text to plug into the comment field. Llijihgph wpokrepoj slkaligihe; lkjslijlie jsill. jjjFluxum flap dum dum. Foo bar zany somethingnew any words will do. Just trying to make some 123456789realistic text to plug into the comment field. Llijihgph wpokrepoj slkaligihe; lkjslijlie jsill. jjjFluxum flap dum dum. Foo bar zany somethingnew any words will do. Just trying to make some 123456789realistic text to plug into the comm</comments><photo><![CDATA[/9j/4AAQSkZJRgABAQEASABIAAD//gAyUHJvY2Vzc2VkIEJ5IGVCYXkgd2l0aCBJbWFnZU1hZ2ljaywgejEuMS4wLiB8fEIy
/9sAQwAGBAUGBQQGBgUGBwcGCAoQCgoJCQoUDg8MEBcUGBgXFBYWGh0lHxobIxwWFiAsICMmJykqKRkfLTAtKDAlKCko/9sA
QwEHBwcKCAoTCgoTKBoWGigoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo/8AAEQgB
dwH0AwERAAIRAQMRAf/EABwAAQACAwEBAQAAAAAAAAAAAAAFBgIDBAcIAf/EAEAQAAICAQIDBQUFBgUCBwAAAAABAgMEBREG
EiEHEzFBUWFxgZGhFCIyQrEIFSNSwdEWNENykiThJTNTZIKy8P/EABkBAQEBAQEBAAAAAAAAAAAAAAACAQMEBf/EACMRAQEA
AgICAwEBAQEBAAAAAAABAhEDEiExE0FRBCIyYUL/2gAMAwEAAhEDEQA/APqkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAA/JyjCLlNqMUt234JAfMnbV2k5F2pQp0fKuqULVXQ6bHFvqk59PXyJtlhN7fS+Jz/AGSnvG3PkjzN+u3UobQAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPot2B8u9v3adnyyLMDSsmVWHzOuEa3t3u3jKX
qvREXy2PPOw3SP8AGPaNpuNqU5WQpm8q3ne/ModUvnsJPKvp9yloa7b6qdu9thDfw5pJAZxakt4tNeqA/QAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADzTtf7Q9P4c0fLwcfKj+8px5Jcv8ApJ+O/t28ETa2PkK/
Ps13XLc66PNTUuSuL8iMrdL455XXhDnw7VnafKzDyq4SUrqZcj5X5bo5yWeq65WXxr0kNN4g1/UdQeZfquqyrxJ/wOW+XLzb
9W/VeRXlN0kczMy9QunfnZNl10n1lZNt7fH3kWW+zbbgazrGlPnwdRyqF4pQse3y8DJbDUq5aJ2uaxhzhDVKqc6rzfLyT296
6fQv5bPbLxy+nsvDfEGn8RadHM065Sj4Tg+kq5ejR2xymU3HK42e0sUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAADaSbb2SA+Zu039obJp1XJ0vg6qpVUzdcs2xc7m10fJHwS9r3JtbpVNK/aD4p0+yP2+deVF+KtrX9Nn9Sd1upp6dwl+0
boeo2Qp1vEswbJdO8rfPD4p7NfUrt+nXfp7Ro+r4GtYccrS8qrJof5oPfb2NeTNll9Mss9u41gAAAAAAAAAwumqqbLH4Qi5P
4AfG37Q3Emlaxk6b+56VC2SlblTX5pPwTMpj7efcGV9/O2Dey+6n8WceW+o9HBPNyv0+icDQcPTOyTUdVlGEcjJ+7juXilvs
vi+p0ymrtylrLg/Knk40NGjpWE6Zx2bhBpRkk9nzLd+KXzZuM35plfKG1XhjUMaU524dtCXi+V7fP4MrrEbQ12NfBfdako+K
8yLxxUypg4tl7sjKqa68senRvYi8cXKgcu7OwtWvx8TJtpox5xlZyTa3mnuk9vHZ9fkcsv8APmO2E7Xy9b4W7acyNcqtcxI5
EnH+FbVtBufpJeHxR1xzuvLlnhN+GrM7Udfois6VmPXjptuEq1ybenr9Te1T1j1ThDjjROJdHxczGz8WF1sE50StSnCXmtn7
S5lE3GprUtWwdNx1dl5EIQfRbdW/ckbcpPbJLUJmccaXVH/pldkz9Ix5V82ReSKmFQ+TxhqeRW5YdFFEX4c285f2JueV9NmM
+3Bj8W67jXb3OrIh4uMoJdPeie+U9quGN9J/E49wZpLKxsimXny7SRc5Yn479O7H4y0i6fL3tkPbOGyKnJjWXCxMYup4WUk6
Mqqe/kpdStxOq6118DWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxZ+rafp8W83Nx6PZZYk/kZbI3Ss6h2j6DiqSosvy5Lypr
e3zexN5I2Y1SuI+1W7Mw8nDxMKGJG+uVfeW2bzSaa3SXgzneX8VMHgcuGcHFW2nd7fLfd7rm3+Jz+Suk459uHUNHjmY8K8ir
uJR6R5o7NFTk3erLxyTtIsHYToegVdoFmJxlTjTqlj2V1Qyku773deO/T8O+x6JPG643/wAepfs/5lMeOOIdN0i53aTju2NU
9904RsSh18+j8SJ/0vL/AJ8voA6OYAAAAAAAAAxtrjbVOua3hNOLXsYHxb+0DwHTwjrqWmXWzwLKY3KNsk5Qbk01v5roZ1+z
flS+BIpW22WtQqlJbN+aXj+pz95x2njjunrUdYr13I0rhnL1RYOmuTubnvy7xW6XTw33Eva0s6xadOuwuD7VkYWs1Zl/jGuM
Wlv06N+mzb+COkunJa9N7TMPKUXn4s3J9Jcj5ovxXh8Ubtjuys3h7VMW3I0fCw7s2MHNVzXK9tnu9vYuoFCz9cyrdSyeXTMf
FhXGNd1UINOMXYuZtrquktn7CMr+OmKK1zhirStLxXPu++yovLnGK25OZ/dXy/Q80vfk6fUei3rx9vuqhq+Gq66q8lqNV8N4
tfkfkyOPOZZ+fDc+PKYePbKelu3SWs7U3OvdRjVCPitvFtnuuMxm68ktyupGUNOboqxtKolOuMlFT32b6njzuOWe8Xr45cZr
J6Vg4leLjVY0ZOarX3m3vvLzK1rw5b35d9NfNZGK8zZPJvwloxUUoryR2nhDOqycIWQjLaFiSlt5+a//AHtK9TafdaZ1xfjG
MvejLJfcb5np+Rxabk061B+x9PqRePGq71qjps4x+7Y4S8X4/wBDPiv1W959x04+TrGF/l8qxpeSlzIz/eJ/mpLH4x1bHklk
VV2r2x2Zs5b9svHPpLYfHWPJ8uZi2VP1i+ZFTlibx1N4nEelZWyhlwjJ+U/ulzOVNwsStdkLY81c4zXrF7lJZAAAAAAAAAAA
AAAAAAAAAAARmoa/pOnb/bNQxqmvyuacvkuplykbqqxqHabotG6xIZOXJecYckfnL+xF5JGzCqlq3a5lLdY1OHiR9Zydkv6I
i8qpx7U3UuPNb1SyUPtmfkVv8tC7uP02Iudq+mkbVTq2Xa3HHrp38Z3S5mZ1ypvGO+jQ7ZR3zdRbXnGv7pc4sqm8knpuhpel
VS2lS7rN+krJczLnD+pvLW2+111cmLjxgvcolfFIjvaq2sUTjNW3qDj57Ld7Hm5Met278We/Cu9rGDRmcPaTruFFQnGTwcqE
fOUVvGXye3wR6pe2Mycbj1tx/Hq37IWncmj6zqEo9ZThTF+5OT/VCTzttvjT6GKSAAAAAAAAAAHy5+19VdDVtOt5Zdzbh8il
t0bjNtr5NGbNPAeELsy/W9P0/EklLKvhRFy8FzyUf6k2Rcysj03jXs54g4Q17F/eFE8yiyucqsrEUpQi49XzdPu7Lr1I69Yr
t2V37bYpvvJb+j3MNOinVZQa5LJxa9pu2aSuBxBn41sbaJylammtn6G9qTGLBmcdahqXJh5lOLz5EYwnc6lz8qk+brv4vq9y
MsvPl0wjt4i1t5t9MJT3c9oxbfgktv7nPjk4+LLP7q8t8nLjh9RG6hfXqMmpeEekevgkeXpdR6fk15cVeJzPlnvyF7y9bRc5
+LRoHcY1s7OZbUVOaW3n4L6s9H8+M7brz8uV078HWKt9rJbe06WIi3aZByoWRFNxl+GW3TY3HG+2XL6djfXw9rLk86ZsXTx+
Jtu2SG7lFxjt182T5UyjRJfhkm/TfYdPw7M3GytdVIayhuMXbOa2e6a8HsO1hqNbsyq1tzK2PglKO5vaX2zWn7TKq+UldjRT
Xi4vYXDGtmVj9swMaz8Nk4P0kt/qReKfTZyX7aaYX49r+y5dkWvOMmvPYzpnjPDe2N9pyjijWcfZWqjIS9Y7P6DvlPcZ0xvp
J4PG1dlirzcXuW/CanvH9OhWPLv2y8aw16rjScFOXduf4ebwfxOku3OzTvT3W68DWAAAAAAAAAAAAxnONcXKcoxivNvZAQmo
8W6Fp+6yNSocl+Wt87+m5Nzkb1qran2raXjxf2PFvva/NNqEf6v6EXli5x1UdT7YM237uLLGx9/BVwdkvr0+hF5r9KnErebx
TrmsNp/vDJi/5pOuHyIueWSukjijpur27Ssnj4cZen3pGzDKnbCN70ChLmzdQuufpzcqLx/nt9pvNJ6jOrG0nESdVEJz/wBv
Mztj/PHLLmtdX2i2a5cfHUE14ye36HWcWMc7yWtDstf/AJuQo+ytf1LmMibax7ulbTknL2zkZbIeWt53ctKucVFeKRzuUXI0
XanBp9eZ+r8jnc29Ve13Vq40yXPDma8upw5L2duKarz/AFzNnlY32WM5cjsi3Hfpv67F8e8cereSy5Wvr39nzR/3R2aYPNHa
eVOeQ/c3svokdY5V6SawAAAAAAAAAAIriTh/SeJNOlha5g05mM+vLYvwv1T8U/cB8bdmfCteR24aRiYEU8SjMllPZ83JXW3J
J/JIzRK+3ZwjZCUJxUoyWzTW6aNHjfGvYPo2r2WZOg5M9LyZde6256W/d4x+HyIuH4qZPGuJuyTjHQXKUtOlnY8f9XDfeLb/
AG/iXyI62LmUqjzozse3u7KL6rF05ZQlF/IxqTw9A4lzWs/G0rUb8ahOU7IY8nGPTbffbr8DOtqscpKktF0vXuJM7uNDwMrM
ljwalyw2UN/WT6G3G5YdTHOY53Jvy+H+K9HsctQ0TPqivGXcycfmt0c8uP8A8X8m3JHVboTas7yD9Gjn0btK6NqSyPtEFLq4
Lpt7S8Lcdpykrug9vAvs52PQ9E114un49CltGEEj04Z+HK4+U9pOvUOvPlkQjN2clcfLZLq/D3lblrNWR2u7AyIpwscW/VJ/
9/qb1xpuvyVNddcrIW1zhFcz67P5P+5PRvZ024d1KrslXJxsgpppNrZrz9pOr+N21RfRut7P2b9A3T9ipSim4Rn18dv6oMZW
Rh3SjCG2z3c2+sn7vJGaa5tkuuxumtc99unwMrI11/h5vX9PIrWvBP12YVfPY5eUV9TZGWtGoYicm0ur+pz5OLfmKwz14rlx
cy/Bs2knZUunLLy9xxxzywdLjMk3ofEGRiZEYRn32JJ9YSfWHuO+OeOXpyyxseiRkpRUovdNbplIfoAAAAAAIXV+KNF0ndZ2
oUQmv9OL5pfJdSblI2Y2qZq3a1hUqS07Btt8lZfJVx+XVkXln0ucdUvU+1TWsybhjXQo38I41e7/AOT3IvLVzjV7MzuINZcn
OV00/wA2Ra3t8CP9ZK1jGmGh5lrisvOUd/KqJs47S54x31aBp1Th3rnf695Lf6HTHhc7y/iQxcCiKaw8OCivzcqX1Z1nDHO8
trqnj2xgpRkk4rfq9/0OkwiLlUZNSk98nIlt6RWxc1E7tY7Yu+6rTa8XJ7/qO8hquXOzq4pJbemyJvLI3ptwz1OMYrd7fEi8
tvpswR2Xr9Nb2d0F/t6si51XVE5XEm7aqrss9snsieyurkoy9X1G7u8DHttm3soU1ub+hm26WrR+yzjTWeWVmFPFrl1c8qxV
/Tx+g1azccvFXY5x3p9u2Fp+PqVDX48W9br3xlyv9R0VM9NvZ92GcSarrFF3E+M9M06qXNYpzTss9iSb+bL0ivrPDxqcLEpx
satV0UwVcILwjFLZIpjcAAAAAAAAAAAAEHpHCOgaNqduoaXpOLi5tsXGd1cNpNN7tfMaE4AAAYyqrk95Qi36tAZJbLZeAGMI
QhvyRjHd7vZbbgZAR+oaJpeoxcc/TsTJT/8AVpjL9UZqN3XnPHnZ7w7jYLu0fT6sLULJdJVSkk15rl329PIzpjfbe1eT5GBZ
ROVd9cq7F02a8ScuPTZntq+0SplyyezRz9LjrxtRlGLSl4vc2ZGndRqsofmKmbOrsesSnTKLm/vLYruy4LHRxPdGa2tfoupW
Oek3FJx4lqt2WTVXa/Vpb/MvtKzVduFqen5Oo41ezrqcZynvJvySWzfXxe5lkN1KfZq7ocuPmQlF+Ut4/XqNU25LdKyUm1Hm
XrFc36bmeW7iLya5wbjJPfflfs39fTpuJN3yb8MdvePbUxg47VUV5y6lxNbrsGdqajF7msQWXiTqu5Zx2T8zhyYbm3TDL6eT
ZvEN1/H0ZvEeVpOFPu1FWOH3t/vS39/0XtOOOWOPiuuWOV8x9Q6PmYOThUx0/JouqhBRXd2KW3Q9Ess8PPZZ7d5rAA3t4gQu
scVaJpEX9v1LHrkvyKXNL5LqTlnjj7qpjb6ec6/21YtTsr0TAlbKKf8AGyXyxXwXV/Q43n+sY7Tg+8q8u1PtK17iHL+z5Ooy
qhPwrr/hw+O39ScpnZu1WPSeoicfMybcjua1Wm3t3sn4HG7xuq69ZZuJ3D0eF8k8y13pP7ylLaPwXmdscOzjlnJ6SVNVNNyp
